site_name: PiE Docs
site_description: Raspberry Pi Controlled Experiment (PiE)
site_author: Robert H Cudmore

repo_name: PiE Repository
repo_url: https://github.com/cudmore/pie
edit_uri: ""

theme:
    name: material
    logo: 'img/icons/video-camera-blue.png'
    favicon: 'img/icons/video-camera-blue.png'
    custom_dir: 'theme'
  
nav:
    - Home: index.md
    - Install: install.md
    - Web Interface: web-interface.md
    - Commander: commander.md
    - Parts: parts.md
    - Wiring - Behavior Box: wiring-behavior-box.md
    - Wiring - Scope: wiring-scope.md
    - Wiring - Treadmill: wiring-treadmill.md
    - Images: images.md
    - Troubleshooting: troubleshooting.md
    - Extras:
        - Rest Interface: rest-interface.md
        - Trial File: trial-file.md
        - GPIO Timing: gpio-timing.md
        - File Server: file-server.md
        - Mount USB Drive: mount-usb-drive.md
    - Implementation details: implementation-details.md
    - Release Notes: release-notes.md
    - About: about.md
   
extra_javascript:
  - 'javascripts/extra.js'


